sudo: required

language: generic

services:
  - docker

before_install:
  - echo "START CREATEING AN IMAGE WITH DOCKERFILE"
  - docker build -t juy4556/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true juy4556/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-app"
  env: "Docker-app-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-258695315070"
  bucket_path: "docker-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secrect_access_key: $AWS_SECRECT_ACCESS_KEY